---
# Homepage configuration
# See https://fontawesome.com/v5/search for icons options

title: "Home Dashboard"
subtitle: "Fiesta"
logo: "logo.png"
# icon: "fas fa-skull-crossbones" # Optional icon

header: true
# header: false
columns: "4"
footer: false
# footer: '<p>Created with <span class="has-text-danger">❤️</span> with <a href="https://bulma.io/">bulma</a>, <a href="https://vuejs.org/">vuejs</a> & <a href="https://fontawesome.com/">font awesome</a> // Fork me on <a href="https://github.com/bastienwirtz/homer"><i class="fab fa-github-alt"></i></a></p>' # set false if you want to hide it.

# Optional theme customization
theme: default
colors:
  light:
    highlight-primary: "Indigo"
    highlight-secondary: "RebeccaPurple"
    highlight-hover: "#5a95f5"
    background: "Lavender"
    card-background: "#ffffff"
    text: "#363636"
    text-header: "#ffffff"
    text-title: "#303030"
    text-subtitle: "#424242"
    card-shadow: rgba(0, 0, 0, 0.1)
    link: "#3273dc"
    link-hover: "#363636"
  dark:
    highlight-primary: "Indigo"
    highlight-secondary: "RebeccaPurple"
    highlight-hover: "#5a95f5"
    background: "#131313"
    card-background: "#2b2b2b"
    text: "#eaeaea"
    text-header: "#ffffff"
    text-title: "#fafafa"
    text-subtitle: "#f5f5f5"
    card-shadow: rgba(0, 0, 0, 0.4)
    link: "#3273dc"
    link-hover: "#ffdd57"

# Optional message
# message:
  # url: http://dim-cloud:5600/
  # style: "is-dark" # See https://bulma.io/documentation/components/message/#colors for styling options.
  # icon: "fa fa-grin"
  # title: "Network Status"
  # content: "This is a dummy homepage demo. <br /> Find more information on <a href='https://github.com/bastienwirtz/homer'>github.com/bastienwirtz/homer</a>"
  # mapping:
    # content: 'status'

# Optional navbar
# links: [] # Allows for navbar (dark mode, layout, and search) without any links
links:
  - name: "Homer documentation"
    icon: "fab fa-github"
    url: "https://github.com/bastienwirtz/homer"
    target: "_blank" # optional html a tag target attribute
  - name: "Pause Network Monitoring"
    icon: "fas fa-eye-slash"
    url: "http://dim-cloud:5600/pause"
    target: "_blank" # optional html a tag target attribute
  # - name: "Refresh"
  #   icon: "fa fa-refresh"
  #   url: "javascript:window.location.href=window.location.href"
  # this will link to a second homer page that will load config from additional-page.yml and keep default config values as in config.yml file
  # see url field and assets/additional-page.yml.dist used in this example:
  #- name: "another page!"
  #  icon: "fas fa-file-alt"
  #  url: "#additional-page" 

# Services
# First level array represent a group.
# Leave only a "items" key if not using group (group name, icon & tagstyle are optional, section separation will not be displayed).
services:


  - name: "Home Network"
    icon: "fas fa-house"
    items:
      - name: "Dim-Cloud"
        # endpoint: "http://localhost:9999/Dim-Cloud"
        url: "http://Dim-Cloud"
        logo: "https://os5.mycloud.com/images/MyCloud_EX2Ultra.e0389527492dea55a865.png"
        subtitle: "Home NAS & Personal Cloud"
        tag: "server"
        target: "_blank"
        # type: Ping
      - name: "Portainer"
        url: "http://dim-cloud:9001/#!/2/docker/containers"
        logo: "https://cdn.worldvectorlogo.com/logos/portainer.svg"
        subtitle: "Docker Management"
        tag: "server"
        target: "_blank"
        type: "Portainer"
        apikey: "ptr_PVSx9Eo98DKB5luvWeBYpsZiYNsZd64xnX/VBENUS6k="
      - name: "FileBrowser"
        url: "http://dim-cloud:56000/files/"
        logo: "https://avatars.githubusercontent.com/u/35781395?s=280&v=4"
        subtitle: "Dim-Cloud Files "
        tag: "server"
        target: "_blank"
      - name: "Transmission"
        endpoint: "http://localhost:9999/dim-cloud/transmission"
        url: "http://dim-cloud/transmission/web/"
        logo: "https://seeklogo.com/images/T/transmission-logo-1B60697576-seeklogo.com.png"
        subtitle: "Torrent Server"
        tag: "server"
        target: "_blank"
        # type: Ping
        # method: "get"
      # - name: "Twonky"
      #   url: "http://192.168.2.100:9000/webconfig"
      #   endpoint: "http://localhost:9999/dim-cloud:9000/webconfig"
      #   logo: "https://developer.asustor.com/uploadIcons/0020_164382_1668033344_twonky-icon1.png"
      #   subtitle: "DLNA Server"
      #   tag: "server"
        # type: Ping
        # target: "_blank" 
      - name: "Home Assistant"
        logo: "https://secure.gravatar.com/avatar/461df105cc6cfcf386ebd5af85b925dc.jpg"
        url: "http://dim-cloud:8123/"
        subtitle: "Smart Home"
        tag: "service"
        target: "_blank"
      # - name: "Stash"
      #   logo: "https://avatars.githubusercontent.com/u/24867479"
      #   url: "http://dim-cloud:9999/"
      #   subtitle: "Video Organizer"
      #   tag: "server"
      #   target: "_blank"
  # - name: "Media"
  #   icon: "fas fa-photo-video"
  #   items:
  #     - name: "Transmission"
  #       logo: "https://seeklogo.com/images/T/transmission-logo-1B60697576-seeklogo.com.png"
  #       subtitle: "Torrent Server"
  #       tag: "server"
  #       url: "http://dim-cloud/transmission/web/"
  #       target: "_blank"
  #     - name: "Twonky"
  #       logo: "https://developer.asustor.com/uploadIcons/0020_164382_1668033344_twonky-icon1.png"
  #       subtitle: "DLNA Server"
  #       tag: "server"
  #       url: "http://192.168.2.100:9000/webconfig"
  #       target: "_blank"        
  #     - name: "Plex"
  #       logo: "https://e1.pngegg.com/pngimages/253/744/png-clipart-clay-os-6-a-macos-icon-plex-yellow-arrow.png"
  #       subtitle: "Media Server"
  #       tag: "server"
  #       url: "http://192.168.2.100:32400/web/index.html#!/"
  #       target: "_blank"
  #     - name: "Stash"
  #       logo: "https://avatars.githubusercontent.com/u/24867479"
  #       url: "http://dim-cloud:9999/"
  #       subtitle: "Video Organizer"
  #       tag: "server"
  #       target: "_blank"


  - name: "Network Services"
    icon: "fas fa-screwdriver-wrench"
    items:
      - name: "Router"
        url: "http://192.168.2.1/"    
        logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a6/Vodafone_icon.svg/1200px-Vodafone_icon.svg.png"
        subtitle: "Home Router"
        tag: "device"
        target: "_blank"
        title: "Network Status"
        content: "hello"
      - name: "Network Monitor"
        type: Ping
        # url: "http://dim-cloud:5600/"
        url: "https://dim-cloud:5443/"        
        logo: "https://assets.dryicons.com/uploads/icon/svg/11258/1bcb293f-8695-423a-a7f2-6239f23794b5.svg"
        subtitle: "Check for internet"
        tag: "server"
        target: "_blank"
        tagstyle: "is-success"
        title: "Network Status"
        content: "hello"
        # background: black
        # mapping:
          # subtitle: 'status'       
      - name: "Fast.com"
        logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b5/Fast.com_logo_vertical.svg/512px-Fast.com_logo_vertical.svg.png?20210105161441"
        subtitle: "Network Speed Test"
        tag: "service"
        url: "https://fast.com/"
        target: "_blank"
      - name: "No-IP"
        logo: "https://d2qr50rz2oof04.cloudfront.net/assets/img/logo/logo-bug.png"
        subtitle: "Dynamic DNS"
        tag: "service"
        url: "https://my.noip.com/"
        target: "_blank"          
      - name: "Uptime Robot"
        logo: "https://play-lh.googleusercontent.com/cUrv0t00FYQ1GKLuOTvv8qjo1lSDjqZC16IOp3Fb6ijew6Br5m4o16HhDp0GBu_Bw8Y"
        subtitle: "Check if services are up"
        tag: "service"
        # keywords: "self hosted reddit"
        url: "https://uptimerobot.com/dashboard"
        target: "_blank"


  - name: "Outlook"
    icon: "fas fa-tasks"
    items:
      - name: "Weather"
        location: "Agios Dimitrios, GR"
        locationId: "263986" 
        apikey: "be4882440fa624f1453216dd2fc9b055" 
        units: "metric"
        background: "circle" # choose which type of background you want behind the image. Can be one of: square, circle, none. Defaults to none.
        type: "OpenWeather"
        target: "_blank"
        tag: "weather"
        tagstyle: "is-info"
      - name: "Kanban Board"
        subtitle: "KanbanTool.com"
        url: "https://dvainanidis.kanbantool.com/b/590831-productivity-board"
        logo: "https://pbs.twimg.com/profile_images/978225524127555584/3p--7p59_400x400.jpg"
        tag: "application"
        target: "_blank"
      - name: "Project Dashboard"
        subtitle: "FreedCamp.com"
        url: "https://freedcamp.com/dashboard"
        logo: "https://seeklogo.com/images/F/freedcamp-logo-E03F65DF3D-seeklogo.com.png"
        tag: "application"
        # keywords: "self hosted reddit"
        target: "_blank"
      - name: "ToDo List"
        subtitle: "To-Do.live.com"
        url: "https://to-do.live.com/tasks/planned"
        logo: "https://downloadr2.apkmirror.com/wp-content/uploads/2018/03/5aa63b2129e8e.png"
        tag: "application"
        target: "_blank"        
      - name: "Time tracker"
        subtitle: "toggl.com"
        url: "https://track.toggl.com/timer"
        logo: "https://cdn.iconscout.com/icon/free/png-256/free-toggl-3521845-2945262.png?f=webp"
        tag: "application"
        target: "_blank"   

  - name: "Websites & AI"
    icon: "fas fa-globe"
    items:
      - name: "ChatGPT"
        logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/04/ChatGPT_logo.svg/2048px-ChatGPT_logo.svg.png"
        url: "https://chat.openai.com/"
        tag: "application"
        target: "_blank"        
      - name: "Gemini"
        logo: "https://upload.wikimedia.org/wikipedia/commons/f/f0/Google_Bard_logo.svg"
        url: "https://gemini.google.com/app"
        tag: "application"
        target: "_blank"
      - name: "Machine Learning"
        logo: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAOEAAADhCAMAAAAJbSJIAAABhlBMVEX///8AhvgAnlP/wgD9QjP/vwAAhfj/w8D/5aen38j+UUMAp2L9QDEAc+mnxfEAgvj/uwAAm0z5QTP/vAD/tgD/sQD/swDkPjD/rADePTD9OikAizrYPC/xQDLrPzEAl0cAkFDe7eZzs5IAkv8Ai0D/+OGq0PzD3v3/ygAAcOrl9/H1LRjvwL1MwZFmrYn89vbjY1r45eSU2b3rr6zxJxDy0M7F3tJMo3d90a8PjvgAl/8AffgAmlVirPqeyLLh7v5JkOj/9NJNovn/4Yawy/H/11cshedjnemSuO0AeOf/8MH//fSDu/v/0j7/opzpoZyBwKb/gnqy1MMxmWbE69z/Y1gQsXXlgXr/tK/mLBj/lI1myaH/c2kwuYLjbGSx5NDnlI/jUUYkll6godH/Mw7AWGviMwWhbJOFfLfISEpjitawXHXVNBu/TVWTdabPQDh1hMipaIq7X3fUX1edoSHCqx9JlELjsg18mjb/2G7/5JGwoSbVqBZjlDyTmTDT5v3lpA2Jq2cQrgGeAAAICUlEQVR4nO2ba3sTRRiGWZYsFQI5k6ZNm0BpC4jUKgcbhZ5AsQdE8EA9i1IOVsATAqLVf+7uzk6aTWZn39nMO7sf3pvvk+u5nmTu6XPpvn0EQRAEQRAEQRAEQRAEQRAEQRAEQRAEQRAEQRAEQRBZYO4gnIgjXoNjNFrAjfIhIOWPIo64uf8wlHeMZvOZz4OZjDykXdoP5YzBbIyPxw4Aef1s5CG3WtCApTcMZvO5MJYHBhz7XnLMbXCJpU+MZWN8Cq7w/LzkmOPj4ISfGcvmcwde4efSg87BSzR6n86VoQHzW3Pyo05CE+4/bCYb4wb8mokyBecK/LL50kg2n3nwdzRfjz2sDS7RoDG+gl8z0abgXIRfNsaMcRZ+zbwJOC6DxtBkCk72jHEHHDDGFJwT8BLfQs7mo9EUHLgxjFw2X8BN8TbwyGwZQ8EUTfChcGOUjiNmYyiY4gL4UAVjfI2Yzecg3BTfKBx7CX7ZfIuWjXEIGhBmCs4ZeInIz1MFU3yndHBWjDF3AG4KxaMzYgwt04WYbAwa8OkiL5suxNzNwvMUxRQcBWOgPU8P6n6QhsnAoHEoX3aBfEfPAx+kIeDGwBo0boyVA2IrjJsuxNyEXzYoE/h8/kAZFlEycstJedD44cdyGRZR2RScdI2xO3VvDBZROnLLSXXQWCksbZdBEZUepGHSHDRmCs7U/R1IxESm4KRojAXHcjqNxsREXMJkpuiS2gS+UbAsy3mw04yNGDtyy1EYNLQaY9FyvISdh82eiOIK40duOSkZ47JXoRvx0XZcRMDILedWKhP4rOOwhFM/NeQRQSO3nFSM0WEVuhGX3BL3IgoqTG4KThrGmOEBXR7vNJuNyBIVpwsxKQwaC043oNNxO9yL2H/NQEduOcYHjY2eCi3r6Y4XUVwieOSWY3oCX3ScnoBO5+dmT8RwhfCRW47CBK6jxJVQhcwYzUZdEDHBdCHG7AQ+Gw7oGuMX77IRRFQaueUYncA7jtUXcclPyCNqNQVHwRhDP09n+irsGqNR74uoxRQcg8aw+iv0LpsnLOFkb0LlkVuOMWNsCCq0nKfb/tc0FDHxdCHG1KCx6wxW6JV4r+EnZBFZhcmnCzF3wR0O9TxdEVXInqd+h5MTPKI2U3DMGOOqOKBlucZohCJqNAVHwRjJB40F0XeUfU932LeURRx2uhBiYgK/HlWhy+Ot3ogJR245+BP4osAUeyU+6SacKCceueWgDxqXJRV6xmAJJ9yEmk3BwTaG2BTdhFP36g3e4fDThRjkQSPCFN2IS9uNoEOND9IwuIOG6EEaYur+TsNPmB9m5JaDOoFHmqJbYqfOfoh6pgsxiBO48EHax4Mtr8QtPdOFGMQJXGKKvRIfeiXqmi7EoBkj9lfoR3y0Xa9v6X6QhoEbo6X2h2LMRRoknPp1cvI3pGgcsDEUH+CF+C+p5RtjG8sUHAVjqBy7+C4koMt9PFNwwINGS+WHCE3oLCCaImAdaoyWyn8+DO6wsIGWjLP6+3sIHe6DJnSsRaxkAdOVCtAY40rnvg+6abwSLyMl42wWK3/AIt5WOlf2x2+4RGcXKRpjrVIpVp5BApauKB28eBqY0Cp0kLIx7GKlWPwTUuK44l/BH0BLtAozONl8Ropuh8XK8/jLpnRC9Wxwic4CRjTGes4L6BJf4knlw49Cr1NMY7zwKyxWi7HGaKn9Cn0+hF6neMaYDhosVqtx2m8nOH72SOrG2CzygNVX8u/p+MUk5y/BL5tZ3dl81uxuhdWq1BilS4k+AG4MB8cYp+wgopdQaozxhP9HG2TJCErEMMbLnG3bPGC1KjGGuik44F8ihjHWbR8esHosukR1U3BSNca1XBAxCFj9K6rEJKbggB/gjqPbGMs2pxsxyhh3h/iYXfjzdEVbNsZmrhvRz+cSYYxkpuAoPE/1GmPE7oElrB37W3jNJDMFJzVjnLJDEb2AtVpVVKLq3xT9gP9QtArX9WTzWc3ZfRFrHv8MXjatm8N+FtwYGp+n03Y/QcTBEttDf9hVuDH0PU+v5QYisoQDxmjdGv7TFIyha9BYHsjXjdj3PC2pjTNiUjDGKVFCFrHPGEkfpGGMDxojwoC2XRt1/z0PVXhOyweaHjTWxRV6EWu10dHeEpM/SMNcN/s87TdFqMXR0R5jDPMgDWN00Bg0RV/EvRLbw0cLMGqMzegKWcRXvEQdpuAoGGPY5+maLJ+LW+IzjabgGJzAI6+ZvYj/tjWagmPMGC+l39Egom+M5NOFGEPGiDZFKGJboyk4hgaNF/EVehHd56k+U3CMGENqit6IbY2m4BiZwOWm6OHVyaGmCzEGJvA4U/Twn9ZsDAODBuSaYVSmtWYLQJ/AAaYIyK1qzhaAPIGvw7+jOd3RApCNATOFH3BEe7YA1EFDOF1EgJCNgTpogE1hV5YRsgUgGiNquhBwDSUbA9EYCqZYR8kWgDaBS6aLPrBMwUGawKEPUg+0bAykQUMwckdViGYKDooxFEyxiZiNgWIMhWsG0RQchEEDborcC9RsAdoHDdB0ESRENQVH+wSuYIqXyNkCNA8aGTIFR7MxFEyxhp4tQOsErjBd4JuCo3UCT3u6EKPRGArThRFTcLQZI3Om4GgbNLIwXYjRZIwMmoKjMIHLnqfw6cKcKThaBg0FU2BOF2K0GCObpuBsnD4C5HTUoLGag1JBni7EHIUTccIIHKOmIAiCIAiCIAiCIAiCIAiCIAiCIAiCIAiCIAiCIAiCiOR/YtxWPZFD9y8AAAAASUVORK5CYII="
        url: "https://developers.google.com/machine-learning"
        tag: "learning"
        target: "_blank"
      - name: "Twitch"
        logo: "https://cdn.worldvectorlogo.com/logos/twitch-purple.svg"
        # subtitle: "Bookmark example"
        tag: "website"
        # keywords: "self hosted reddit"
        url: "https://www.twitch.tv/"
        target: "_blank"
      - name: "YouTube"
        logo: "https://upload.wikimedia.org/wikipedia/commons/e/ef/Youtube_logo.png?20220706172052"
        tag: "website"
        url: "https://www.youtube.com/playlist?list=WL"
        target: "_blank"

  - name: "Develompent"
    icon: "fab fa-dev"
    items:
      - name: "Dev App"
        url: "http://192.168.2.102/"
        # endpoint: "http://192.168.2.102/ping"
        logo: "https://exoffender.org/wp-content/uploads/2018/01/house-icon.png"
        # type: Ping  # needs ACAO
        # method: "get"
        tag: "development"
        target: "_blank"
      - name: "Railway"
        logo: "https://railway.app/brand/logo-light.png"
        url: "https://railway.app/dashboard"
        # subtitle: "Another application"
        tag: "development"
        target: "_blank"        
      - name: "GitHub"
        logo: "https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png"
        url: "https://github.com/DimVai?tab=repositories"
        # subtitle: "Another application"
        tag: "development"
        target: "_blank"
      - name: "CodePen"
        logo: "https://cpwebassets.codepen.io/assets/social/facebook-default-05cf522ae1d4c215ae0f09d866d97413a2204b6c9339c6e7a1b96ab1d4a7340f.png"
        url: "https://codepen.io/your-work/"
        # subtitle: "Another application"
        tag: "development"
        target: "_blank"

  - name: "Access From Internet"
    icon: "fas fa-campground"
    items:
      - name: "Dim-Cloud"
        logo: "https://os5.mycloud.com/images/MyCloud_EX2Ultra.e0389527492dea55a865.png"
        url: "http://vainanidis.ddns.net:56888/"
        subtitle: "Home NAS & Personal Cloud"
        tag: "server"
        target: "_blank"
        # type: Ping
      - name: "Transmission"
        url: "http://vainanidis.ddns.net:56888/transmission/web/"
        logo: "https://seeklogo.com/images/T/transmission-logo-1B60697576-seeklogo.com.png"
        subtitle: "Torrent Server"
        tag: "server"
        target: "_blank"
        # type: Ping
      # - name: "Portainer"
      #   logo: "https://cdn.worldvectorlogo.com/logos/portainer.svg"
      #   url: "http://dim-cloud:9001/#!/home"
      #   subtitle: "Docker Management"
      #   tag: "server"
      #   target: "_blank"